/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as ExercicioIdRouteImport } from './routes/exercicio.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicioIdRoute = ExercicioIdRouteImport.update({
  id: '/exercicio/$id',
  path: '/exercicio/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercicios': typeof ExerciciosRoute
  '/importar': typeof ImportarRoute
  '/perfis': typeof PerfisRoute
  '/treino': typeof TreinoRoute
  '/treinos': typeof TreinosRoute
  '/exercicio/$id': typeof ExercicioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercicios': typeof ExerciciosRoute
  '/importar': typeof ImportarRoute
  '/perfis': typeof PerfisRoute
  '/treino': typeof TreinoRoute
  '/treinos': typeof TreinosRoute
  '/exercicio/$id': typeof ExercicioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercicios': typeof ExerciciosRoute
  '/importar': typeof ImportarRoute
  '/perfis': typeof PerfisRoute
  '/treino': typeof TreinoRoute
  '/treinos': typeof TreinosRoute
  '/exercicio/$id': typeof ExercicioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercicios'
    | '/importar'
    | '/perfis'
    | '/treino'
    | '/treinos'
    | '/exercicio/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercicios'
    | '/importar'
    | '/perfis'
    | '/treino'
    | '/treinos'
    | '/exercicio/$id'
  id:
    | '__root__'
    | '/'
    | '/exercicios'
    | '/importar'
    | '/perfis'
    | '/treino'
    | '/treinos'
    | '/exercicio/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExerciciosRoute: typeof ExerciciosRoute
  ImportarRoute: typeof ImportarRoute
  PerfisRoute: typeof PerfisRoute
  TreinoRoute: typeof TreinoRoute
  TreinosRoute: typeof TreinosRoute
  ExercicioIdRoute: typeof ExercicioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicio/$id': {
      id: '/exercicio/$id'
      path: '/exercicio/$id'
      fullPath: '/exercicio/$id'
      preLoaderRoute: typeof ExercicioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExerciciosRoute: ExerciciosRoute,
  ImportarRoute: ImportarRoute,
  PerfisRoute: PerfisRoute,
  TreinoRoute: TreinoRoute,
  TreinosRoute: TreinosRoute,
  ExercicioIdRoute: ExercicioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
